[package]
name = "sao"
version = "0.1.0"
authors = ["Joel Oredsson <joel_ored@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subprocess = "0.2.6"
crossterm = "0.11"
nix = "0.20.0"
regex = "1"
